# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\user\durgesh.n\workspace\pcgiShapeManager\ui\pcgiShapeManegerUI.ui'
#
# Created: Fri May 26 16:23:17 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 706)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.baseMeshName_le = QtGui.QLineEdit(self.centralwidget)
        self.baseMeshName_le.setEnabled(False)
        self.baseMeshName_le.setMinimumSize(QtCore.QSize(0, 20))
        self.baseMeshName_le.setObjectName("baseMeshName_le")
        self.horizontalLayout_2.addWidget(self.baseMeshName_le)
        self.selectBaseMesh_tb = QtGui.QToolButton(self.centralwidget)
        self.selectBaseMesh_tb.setObjectName("selectBaseMesh_tb")
        self.horizontalLayout_2.addWidget(self.selectBaseMesh_tb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.baseMeshShape_le = QtGui.QLineEdit(self.centralwidget)
        self.baseMeshShape_le.setEnabled(False)
        self.baseMeshShape_le.setMinimumSize(QtCore.QSize(0, 20))
        self.baseMeshShape_le.setObjectName("baseMeshShape_le")
        self.verticalLayout.addWidget(self.baseMeshShape_le)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainfileter_le = QtGui.QLineEdit(self.centralwidget)
        self.mainfileter_le.setMinimumSize(QtCore.QSize(0, 20))
        self.mainfileter_le.setObjectName("mainfileter_le")
        self.verticalLayout_6.addWidget(self.mainfileter_le)
        self.interFileter_le = QtGui.QLineEdit(self.centralwidget)
        self.interFileter_le.setMinimumSize(QtCore.QSize(0, 20))
        self.interFileter_le.setObjectName("interFileter_le")
        self.verticalLayout_6.addWidget(self.interFileter_le)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.loadShapes_tb = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadShapes_tb.sizePolicy().hasHeightForWidth())
        self.loadShapes_tb.setSizePolicy(sizePolicy)
        self.loadShapes_tb.setMaximumSize(QtCore.QSize(70, 90))
        self.loadShapes_tb.setObjectName("loadShapes_tb")
        self.horizontalLayout_3.addWidget(self.loadShapes_tb)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.mainShapes_tw = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainShapes_tw.sizePolicy().hasHeightForWidth())
        self.mainShapes_tw.setSizePolicy(sizePolicy)
        self.mainShapes_tw.setMinimumSize(QtCore.QSize(150, 190))
        self.mainShapes_tw.setObjectName("mainShapes_tw")
        self.mainShapes_tw.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.mainShapes_tw)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addShapes_b = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addShapes_b.sizePolicy().hasHeightForWidth())
        self.addShapes_b.setSizePolicy(sizePolicy)
        self.addShapes_b.setMinimumSize(QtCore.QSize(100, 25))
        self.addShapes_b.setMaximumSize(QtCore.QSize(150, 60))
        self.addShapes_b.setObjectName("addShapes_b")
        self.horizontalLayout_5.addWidget(self.addShapes_b)
        self.mirrorShapes_b = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorShapes_b.sizePolicy().hasHeightForWidth())
        self.mirrorShapes_b.setSizePolicy(sizePolicy)
        self.mirrorShapes_b.setMinimumSize(QtCore.QSize(100, 25))
        self.mirrorShapes_b.setMaximumSize(QtCore.QSize(150, 60))
        self.mirrorShapes_b.setObjectName("mirrorShapes_b")
        self.horizontalLayout_5.addWidget(self.mirrorShapes_b)
        self.makeConnections_b = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeConnections_b.sizePolicy().hasHeightForWidth())
        self.makeConnections_b.setSizePolicy(sizePolicy)
        self.makeConnections_b.setMinimumSize(QtCore.QSize(100, 25))
        self.makeConnections_b.setMaximumSize(QtCore.QSize(150, 60))
        self.makeConnections_b.setObjectName("makeConnections_b")
        self.horizontalLayout_5.addWidget(self.makeConnections_b)
        self.refreshUI_b = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshUI_b.sizePolicy().hasHeightForWidth())
        self.refreshUI_b.setSizePolicy(sizePolicy)
        self.refreshUI_b.setMinimumSize(QtCore.QSize(100, 25))
        self.refreshUI_b.setMaximumSize(QtCore.QSize(150, 60))
        self.refreshUI_b.setObjectName("refreshUI_b")
        self.horizontalLayout_5.addWidget(self.refreshUI_b)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.baseMeshName_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "select baseMesh", None, QtGui.QApplication.UnicodeUTF8))
        self.selectBaseMesh_tb.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.baseMeshShape_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "baseMeshShape", None, QtGui.QApplication.UnicodeUTF8))
        self.mainfileter_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "*Filters*", None, QtGui.QApplication.UnicodeUTF8))
        self.interFileter_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "*Filters*", None, QtGui.QApplication.UnicodeUTF8))
        self.loadShapes_tb.setText(QtGui.QApplication.translate("MainWindow", "loadShapes", None, QtGui.QApplication.UnicodeUTF8))
        self.addShapes_b.setText(QtGui.QApplication.translate("MainWindow", "addShapes", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorShapes_b.setText(QtGui.QApplication.translate("MainWindow", "mirrorShapes", None, QtGui.QApplication.UnicodeUTF8))
        self.makeConnections_b.setText(QtGui.QApplication.translate("MainWindow", "makeConnections", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshUI_b.setText(QtGui.QApplication.translate("MainWindow", "refreshUI", None, QtGui.QApplication.UnicodeUTF8))

